backend:
  name: git-gateway
  branch: main # Branch to update (master, main, etc.)

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog_en"
    label: "Blog Posts (EN)"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Language", name: "lang", widget: "hidden", default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string", default: "Story"}
      - {label: "Short Description", name: "description", widget: "text", required: false, hint: "Used for the blog feed excerpt"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "blog_cs"
    label: "Blog Posts (CS)"
    folder: "cs/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post_cs"}
      - {label: "Language", name: "lang", widget: "hidden", default: "cs"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string", default: "Příběh"}
      - {label: "Short Description", name: "description", widget: "text", required: false, hint: "Použito pro zkrácený text na hlavní stránce blogu"}
      - {label: "Body", name: "body", widget: "markdown"}
